config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root :to => 'home#index'

  resources :students
  resources :instructors
  resources :cohorts do
    resources :cohorts_student, only: [:new, :create]
    resources :cohorts_instructors, only: [:new, :create]
  end
  resources :courses
  resources :cohorts_instructors
  resources :cohorts_students

end

app/models/cohorts_instructor.rb
class CohortsInstructor < ApplicationRecord
  belongs_to :cohort
  belongs_to :instructor
end

app/controllers/cohorts_instructors_controller.rb
class CohortsInstructorsController < ApplicationController
  before_action :authenticate_user!
  skip_before_action :verify_authenticity_token, only: [:destroy]
    
  def index
    @cohorts_instructors = CohortsInstructor.all.order(:cohort_id)
  end

  def show
    @cohorts_instructor = CohortsInstructor.find(params[:id])
  end

  def new
    @cohorts = Cohort.all.map{ |c| [c.name, c.id]}
    @instructors = Instructor.all.map{|i| ["#{i.f_name} #{i.l_name}", i.id]}
    @cohorts_instructor = CohortsInstructor.new 
  end

  def create
    CohortsInstructor.create(cohort_instructor_params)
    flash[:success] = "Cohort Instructor has been successfully added."
    redirect_to cohorts_instructors_path
  end

  def edit
    @cohorts_instructor = CohortsInstructor.find(params[:id])
    @cohorts = Cohort.all.map{ |c| [c.name, c.id]}
    @instructors = Instructor.all.map{|i| ["#{i.f_name} #{i.l_name}", i.id]}
  end

  def update
    cohorts_instructor = CohortsInstructor.find(params[:id])
    cohorts_instructor .update(cohort_instructor_params)
    redirect_to cohorts_instructors_path
  end

  def destroy
    CohortsInstructor.destroy(params[:id])
    render json: {status: 'success', message: 'Cohort Instructor was successfully deleted'}
  end

  private

  def cohort_instructor_params
    params.require(:cohorts_instructor).permit(:instructor_id, :cohort_id)
  end
end

app/helpers/cohorts_instructor_helper.rb
module CohortsInstructorHelper
end

app/views/cohorts_instructors/_form.html.erb
<%= form_for @cohorts_instructor do |f| %>

  <div>
    <% f.label :cohort %>Cohort: 
    <%= f.select :cohort_id, options_for_select(@cohorts, @cohorts_instructor.cohort_id) %>
  </div>

  <div>
    <% f.label :instructor %>Instructor: 
    <%= f.select :instructor_id, options_for_select(@instructors, @cohorts_instructor.instructor_id) %>
  </div>

  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/cohorts_instructors/edit.html.erb
<h3>Edit Cohort Instructor: <%= @cohorts_instructor.cohort.name %> - <%= @cohorts_instructor.instructor.f_name %> <%= @cohorts_instructor.instructor.l_name %></h3>

<%= render 'form' %>
<br>
<div class="links">
  <%= link_to 'Cancel', cohorts_instructors_path, 'class': 'btn btn-outline-secondary btn-lg btn-block' %>
</div>

app/views/cohorts_instructors/index.html.erb
<h3>Cohort Instructors</h3>

<p>This is where you can create, display, edit, and remove Cohort Instructors</p>

<div class="main-img-div auto-margin">
  <%= image_tag image_path('books.jpg'), alt: 'books image' %>
</div>

<div class="content">
  <br />
  <%= link_to 'Assign New Cohort Instructor', new_cohorts_instructor_path, 'class': 'btn btn-outline-secondary btn-lg btn-block' %>

  <br />

  <% if @cohorts_instructors!=[] %>
  
    <table class="table table-striped table-hover">
      <thead class="thead-light">
        <tr>
          <th scope="col">Cohort</th>
          <th scope="col">Instructor</th>
          <th scope="col">Assigned</th>
          <th scope="col">Options</th>
        </tr>
      </thead>

      <tbody>
        <% @cohorts_instructors.each do |cohort_instructor| %>
        <tr class="cohort-instructor-div">
          <th scope="row"><%= cohort_instructor.cohort.name%></th>
          <td><%= cohort_instructor.instructor.f_name %> <%= cohort_instructor.instructor.l_name %></td>
          <td><%= cohort_instructor.created_at.strftime('%Y-%m-%d') %></td>
          <td class="links">
            <%= link_to 'View Cohort', cohort_path(cohort_instructor.cohort.id) %>
            <%= link_to 'Edit', edit_cohorts_instructor_path(cohort_instructor) %>
            <%= link_to 'Remove', cohort_instructor, class: 'delete-cohort_instructor' %>
          </td>
        </tr>
        <% end %> 
      </tbody>
    </table>
    
  <% end %>  
</div>

app/views/cohorts_instructors/new.html.erb
<p>
  This is where you can assign an Instructor to a Cohort.
</p>

<h3>Add a new Instructor to this Cohort</h3>

<div>
  <%= render 'form' %>
</div>


<br>
<div class="links">
  <%= link_to 'Cancel', cohorts_instructors_path, 'class': 'btn btn-outline-secondary btn-lg btn-block' %>
</div>