config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root :to => 'home#index'

  resources :students
  resources :instructors
  resources :cohorts do
    resources :cohorts_student, only: [:new, :create]
    resources :cohorts_instructors, only: [:new, :create]
  end
  resources :courses
  resources :cohorts_instructors
  resources :cohorts_students

end

app/models/cohort.rb
class Cohort < ApplicationRecord
  validates :name, :start_date, :end_date, presence: true
  has_many :cohorts_students, dependent: :destroy
  has_many :cohorts_instructors, dependent: :destroy
  has_many :students, through: :cohorts_students, dependent: :destroy
  has_many :instructors, through: :cohorts_instructors, dependent: :destroy
  belongs_to :course
end

app/controllers/cohorts_controller.rb
class CohortsController < ApplicationController
  before_action :authenticate_user!
  skip_before_action :verify_authenticity_token, only: [:destroy]

  def index
    @cohorts = Cohort.all.order(:start_date)
  end

  def show
    @cohort = Cohort.find(params[:id])
    @instructors = @cohort.instructors.all.order(:l_name)
    @students = @cohort.students.all.order(:l_name)

  end

  def new
    @cohort = Cohort.new
    @courses = Course.all.map{ |c| [c.name, c.id]}
    @cohorts = Cohort.all.map{ |c| [c.name, c.id]}
    @instructors = Instructor.all.map{|i| ["#{i.f_name} #{i.l_name}", i.id]}
    @students = Student.all.map{|s| ["#{s.f_name} #{s.l_name}", s.id]}
  end

  def create
    Cohort.create(cohort_params)
    flash[:success] = "Cohort has been successfully created."
    redirect_to cohorts_path
  end

  def edit
    @cohort = Cohort.find(params[:id])
    @courses = Course.all.map{ |c| [c.name, c.id]}
  end

  def update
    cohort = Cohort.find(params[:id])
    cohort.update(cohort_params)
    redirect_to cohorts_path
  end

  def destroy
    Cohort.destroy(params[:id])
    render json: {status: 'success', message: 'Cohort was successfully deleted'}
  end

  private

  def cohort_params
    params.require(:cohort).permit(:name, :start_date, :end_date, :course, :instructors, :students, :course_id, :instructor_ids, :student_ids)
  end

end

app/helpers/cohorts_helper.rb
module CohortsHelper
end

app/views/cohorts/_form.html.erb
<%= form_for @cohort do |f| %>
  <div>
    <% f.label :name %> Name: 
    <%= f.text_field :name %>
  </div>

  <div>
    <% f.label :start_date %> Start Date: 
    <%= f.date_field :start_date %>
  </div>

  <div>
    <% f.label :end_date %> End Date: 
    <%= f.date_field :end_date %>
  </div>
  
  <div>
    <% f.label :course %>Course: 
    <%= f.select :course_id, options_for_select(@courses, @cohort.course_id) %>
  </div>


  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/cohorts/edit.html.erb
<h3>Edit Cohort: <%= @cohort.name %></h3>

<%= render 'form' %>
<br>
<div  class="links">
  <%= link_to 'Cancel', cohorts_path, 'class': 'btn btn-outline-secondary btn-lg btn-block' %>
</div>

app/views/cohorts/index.html.erb
<h3>Cohorts</h3>

<p>This is where you can create, display, edit, and remove Cohorts</p>

<div class="main-img-div auto-margin">
  <%= image_tag image_path('classroom.jpg'), alt: 'classroom image' %>
</div>

<div class="content">
  <br />
  <%= link_to 'Add New Cohort', new_cohort_path, 'class': 'btn btn-outline-secondary btn-lg btn-block' %>
  
  <br />
  
  <% if @cohorts!=[] %>

    <table class="table table-striped table-hover">
      <thead class="thead-light">
        <tr>
          <th scope="col">Id #</th>
          <th scope="col">Name</th>
          <th scope="col">Created</th>
          <th scope="col">Options</th>
        </tr>
      </thead>

      <tbody>
        <% @cohorts.each do |cohort| %>
        <tr class="cohort-div">
          <th scope="row"><%= cohort.id%></th>
          <td><%= cohort.name %></td>
          <td><%= cohort.created_at.strftime('%Y-%m-%d %H:%M:%S') %></td>
          <td class="links">
            <%= link_to 'View', cohort_path(cohort) %>
            <%= link_to 'Edit', edit_cohort_path(cohort) %>
            <%= link_to 'Delete', cohort, class: 'delete-cohort' %>
          </td>
        </tr>
        <% end %> 
      </tbody>
    </table>
    
  <% end %>
</div>

app/views/cohorts/new.html.erb
<h3>Add a new Cohort</h3>

<%= render 'form' %>
<br>
<div  class="links">
  <%= link_to 'Cancel', cohorts_path, 'class': 'btn btn-outline-secondary btn-lg btn-block' %>
</div>

app/views/cohorts/show.html.erb
<h3>Cohort Details:</h3>

  <div>
    Cohort: <%= @cohort.name %>
  </div>

  <div>
    Start Date: <%= @cohort.start_date %>
  </div>

  <div>
    End Date: <%= @cohort.end_date %>
  </div>

  <div>
    Instructors: <% @instructors.each do |instructor| %>[ <%= instructor.f_name%> <%= instructor.l_name%>, <%= link_to 'View', instructor_path(instructor) %> ] <% end %>
  </div>

  <div>
    Students: <% @students.each do |student| %>[ <%= student.f_name%> <%= student.l_name%>, <%= link_to 'View', student_path(student) %> ] <% end %>
  </div>

<br>
<div class="links">
  <%= link_to 'Back', cohorts_path, 'class': 'btn btn-outline-secondary btn-lg btn-block' %>
</div>