config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root :to => 'home#index'

  resources :students
  resources :instructors
  resources :cohorts do
    resources :cohorts_student, only: [:new, :create]
    resources :cohorts_instructors, only: [:new, :create]
  end
  resources :courses
  resources :cohorts_instructors
  resources :cohorts_students

end

app/models/instructor.rb
class Instructor < ApplicationRecord
  validates :f_name, :l_name, :birthday, :education, presence: true
  has_many :cohorts_instructors, dependent: :destroy
  has_many :cohorts, through: :cohorts_instructors, dependent: :destroy
end

app/controllers/instructors_controller.rb
class InstructorsController < ApplicationController
  before_action :authenticate_user!
  skip_before_action :verify_authenticity_token, only: [:destroy]
  
  def index
    @instructors = Instructor.all.order(:l_name)
  end

  def show
    @instructor = Instructor.find(params[:id])
  end

  def new
    @instructor = Instructor.new
  end

  def create
    Instructor.create(instructor_params)
    flash[:success] = "Instructor has been successfully created."
    redirect_to instructors_path
  end

  def edit
    @instructor = Instructor.find(params[:id])
  end

  def update
    instructor = Instructor.find(params[:id])
    instructor.update(instructor_params)
    redirect_to instructors_path
  end

  def destroy
    Instructor.destroy(params[:id])
    render json: {status: 'success', message: 'Instructor was successfully deleted'}
  end

  private

  def instructor_params
    params.require(:instructor).permit(:f_name, :l_name, :birthday, :salary, :education)
  end

end

app/helpers/instructors_helper.rb
module InstructorsHelper
end

app/views/instructors/_form.html.erb
<%= form_for @instructor do |f| %>
  <div>
    <% f.label :f_name %>First Name: 
    <%= f.text_field :f_name %>
  </div>

  <div>
    <% f.label :l_name %>Last Name: 
    <%= f.text_field :l_name %>
  </div>

  <div>
    <% f.label :birthday %>Birthday: 
    <%= f.date_field :birthday %>
  </div>

  <div>
    <% f.label :salary %>Salary: 
    <%= f.number_field :salary %>
  </div>

  <div>
    <% f.label :education %>Highest Level of Education: 
    <%= f.select :education, ['HS', 'College', 'Masters', 'PhD'] %>
  </div>
  
  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/instructors/edit.html.erb
<h3>Edit Instructor: <%= @instructor.f_name %> <%= @instructor.l_name %></h3>

<%= render 'form' %>
<br>
<div  class="links">
  <%= link_to 'Cancel', instructors_path, 'class': 'btn btn-outline-secondary btn-lg btn-block' %>
</div>

app/views/instructors/index.html.erb
<h3>Instructors</h3>

<p>This is where you can create, display, edit, and remove Instructors</p>

<div class="main-img-div auto-margin">
  <%= image_tag image_path('apple.jpg'), alt: 'apple image' %>
</div>

<div class="content">
  <br />
  <%= link_to 'Add New Instructor', new_instructor_path, 'class': 'btn btn-outline-secondary btn-lg btn-block' %>

  <br>

  <% if @instructors!=[] %>

    <table class="table table-striped table-hover">
      <thead class="thead-light">
        <tr>
          <th scope="col">Id #</th>
          <th scope="col">First</th>
          <th scope="col">Last</th>
          <th scope="col">Options</th>
        </tr>
      </thead>

      <tbody>
        <% @instructors.each do |instructor| %>
        <tr class="instructor-div">
          <th scope="row"><%= instructor.id%></th>
          <td><%= instructor.f_name %></td>
          <td><%= instructor.l_name %></td>
          <td class="links">
            <%= link_to 'View', instructor_path(instructor) %>
            <%= link_to 'Edit', edit_instructor_path(instructor) %>
            <%= link_to 'Delete', instructor, class: 'delete-instructor' %>
          </td>
        </tr>
        <% end %> 
      </tbody>
    </table>

  <% end %>
</div>

app/views/instructors/new.html.erb
<h3>Add a new Instructor</h3>

<%= render 'form' %>
<br>
<div  class="links">
  <%= link_to 'Cancel', instructors_path, 'class': 'btn btn-outline-secondary btn-lg btn-block' %>
</div>

app/views/instructors/show.html.erb
<h3>Instructor Details:</h3>

<table class="table table-striped table-hover">
  <thead class="thead-light">
    <tr>
      <th scope="col">Id #</th>
      <th scope="col">First</th>
      <th scope="col">Last</th>
      <th scope="col">Birthday</th>
      <th scope="col">Salary</th>
      <th scope="col">Education</th>
      <th scope="col">Registered</th>
      <th scope="col">Last Updated</th>
      <th scope="col">Options</th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <th scope="row"><%= @instructor.id%></th>
      <td><%= @instructor.f_name %></td>
      <td><%= @instructor.l_name %></td>
      <td><%= @instructor.birthday.strftime("%m/%d/%Y") %></td>
      <td><%= number_to_currency(@instructor.salary, precision: 0) %></td>
      <td><%= @instructor.education %></td>
      <td><%= @instructor.created_at.strftime('%Y-%m-%d %H:%M:%S') %></td>
      <td><%= @instructor.updated_at.strftime('%Y-%m-%d %H:%M:%S') %></td>
      <td class="links">
        <%= link_to 'Edit', edit_instructor_path(@instructor) %>
      </td>
    </tr>
  </tbody>
</table>

<br>
<div  class="links">
  <%= link_to 'Back', instructors_path, 'class': 'btn btn-outline-secondary btn-lg btn-block' %>
</div>