config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root :to => 'home#index'

  resources :students
  resources :instructors
  resources :cohorts do
    resources :cohorts_student, only: [:new, :create]
    resources :cohorts_instructors, only: [:new, :create]
  end
  resources :courses
  resources :cohorts_instructors
  resources :cohorts_students

end

app/models/cohorts_student.rb
class CohortsStudent < ApplicationRecord
  belongs_to :cohort
  belongs_to :student
end

app/controllers/cohorts_students_controller.rb
class CohortsStudentsController < ApplicationController
  before_action :authenticate_user!
  skip_before_action :verify_authenticity_token, only: [:destroy]

  def index
    @cohorts_students  = CohortsStudent.all.order(:cohort_id)
  end

  def show
    @cohorts_student = CohortsStudent.find(params[:id])
  end

  def new
    @cohorts = Cohort.all.map{ |c| [c.name, c.id]}
    @students = Student.all.map{|i| [i.f_name, i.id]}
    @cohorts_student = CohortsStudent.new 
  end

  def create
    CohortsStudent.create(cohort_instructor_params)
    flash[:success] = "Cohort Student has been successfully added."
    redirect_to cohorts_students_path
  end

  def edit
    @cohorts_student = CohortsStudent.find(params[:id])
    @cohorts = Cohort.all.map{ |c| [c.name, c.id]}
    @students = Student.all.map{|i| ["#{i.f_name} #{i.l_name}", i.id]}
  end

  def update
    cohorts_student = CohortsStudent.find(params[:id])
    cohorts_student.update(cohort_instructor_params)
    redirect_to cohorts_students_path
  end

  def destroy
    CohortsStudent.destroy(params[:id])
    render json: {status: 'success', message: 'Cohort Student was successfully deleted'}
  end

  private

  def cohort_instructor_params
    params.require(:cohorts_student).permit(:student_id, :cohort_id)
  end
end

app/helpers/cohorts_students_helper.rb
module CohortsStudentsHelper
end

app/views/cohorts_students/_form.html.erb
<%= form_for @cohorts_student do |f| %>

  <div>
    <% f.label :cohort %>Cohort: 
    <%= f.select :cohort_id, options_for_select(@cohorts, @cohorts_student.cohort_id) %>
  </div>

  <div>
    <% f.label :student %>Student: 
    <%= f.select :student_id, options_for_select(@students, @cohorts_student.student_id) %>
  </div>

  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/cohorts_students/edit.html.erb
<h3>Edit Cohort Instructor: <%= @cohorts_student.cohort.name %> - <%= @cohorts_student.student.f_name %> <%= @cohorts_student.student.l_name %></h3>

<%= render 'form' %>
<br>
<div  class="links">
  <%= link_to 'Cancel', cohorts_students_path, 'class': 'btn btn-outline-secondary btn-lg btn-block' %>
</div>

app/views/cohorts_students/index.html.erb
<h3>Cohort Students</h3>

<p>This is where you can create, display, edit, and remove Cohort Students</p>

<div class="main-img-div auto-margin">
  <%= image_tag image_path('study.jpg'), alt: 'study image' %>
</div>

<div class="content">
  <br />
  <%= link_to "Assign New Cohort Student", new_cohorts_student_path, 'class': 'btn btn-outline-secondary btn-lg btn-block' %>

  <br />

  <% if @cohorts_students!=[] %>

    <table class="table table-striped table-hover">
      <thead class="thead-light">
        <tr>
          <th scope="col">Cohort</th>
          <th scope="col">Student</th>
          <th scope="col">Registered</th>
          <th scope="col">Options</th>
        </tr>
      </thead>

      <tbody>
        <% @cohorts_students.each do |cohort_student| %>
        <tr class="cohort-student-div">
          <td><%= cohort_student.cohort.name %></td>
          <td><%= cohort_student.student.f_name %> <%= cohort_student.student.l_name %></td>
          <td><%= cohort_student.created_at.strftime("%Y-%m-%d")%></td>
          <td class="links">
            <%= link_to "View Cohort",  cohort_path(cohort_student.cohort.id) %>
            <%= link_to "Edit", edit_cohorts_student_path(cohort_student) %>
            <%= link_to "Unregister", cohort_student, class: "delete-cohort-student" %>
          </td>
        </tr>
        <% end %> 
      </tbody>
    </table>

  <% end %>

</div>

app/views/cohorts_students/new.html.erb
<h3>Add a new Student to this Cohort</h3>

<div>
  <%= render 'form' %>
</div>

<br>
<div  class="links">
  <%= link_to 'Cancel', cohorts_students_path, 'class': 'btn btn-outline-secondary btn-lg btn-block' %>
</div>